server:
  port: 8087

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
        - id: user-auth-route
          uri: lb://user-service
          predicates:
            - Path=/api/users/login,/api/users/register

        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: notice-service
          uri: lb://notice-service
          predicates:
            - Path=/api/notices/**

        - id: pet-service
          uri: lb://pet-service
          predicates:
            - Path=/api/pets/**

        - id: map-service
          uri: lb://map-service
          predicates:
            - Path=/api/maps/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**