server:
  port: 8085

info:
  app:
    name: "Purrsuit Pet Service"
spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/pet_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: pet-matching-group # Unikalna nazwa grupy dla tego serwisu
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        # Pozwalamy na deserializację z dowolnego pakietu (bezpieczne rozwiązanie przy mikroserwisach)
        spring.json.trusted.packages: "*"

llm:
  api:
    url: https://api.groq.com/openai/v1
    key: ${GROQ_API_KEY}
    model: llama-3.3-70b-versatile