server:
  port: 8086

keycloak:
  server-url: http://keycloak:8080
  realm: purrsuit-realm
  admin-username: admin
  admin-password: admin
  client-id: purrsuit-client

spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/user_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
